/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mxgraph.model.mxGraphModel;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.util.mxConstants;
import com.mxgraph.util.mxUtils;
import com.mxgraph.view.mxGraph;
import com.mxgraph.view.mxStylesheet;
import java.awt.BorderLayout;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class Tela extends javax.swing.JFrame {

    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        mxGraph graph = new mxGraph();
        Object parent = graph.getDefaultParent();

        mxStylesheet stylesheet = graph.getStylesheet();
        HashMap<String, Object> style = new HashMap<>();
        style.put(mxConstants.STYLE_SHAPE, mxConstants.SHAPE_ELLIPSE);
        style.put(mxConstants.STYLE_OPACITY, 50);
        style.put(mxConstants.STYLE_FONTCOLOR, "#774400");
        stylesheet.putCellStyle("ROUNDED", style);

        //1cm ~ 38px
        int escala = 38;
        
        graph.getModel().beginUpdate();
        try {
            Object v1 = graph.insertVertex(parent, null, "v1", escala * 5, escala * 4, 15,
                    15, "ROUNDED");
            Object v2 = graph.insertVertex(parent, null, "v2", escala * 20, escala * 4,
                    15, 15, "ROUNDED");
            Object v3 = graph.insertVertex(parent, null, "v3", escala * 23, escala * 10, 15,
                    15, "ROUNDED");
            Object v4 = graph.insertVertex(parent, null, "v4", escala * 8, escala * 10,
                    15, 15, "ROUNDED");
            graph.insertEdge(parent, null, "45", v1, v2);
            graph.insertEdge(parent, null, "500", v1, v3);
            graph.insertEdge(parent, null, "100", v2, v3);
            graph.insertEdge(parent, null, "65", v3, v4);
            graph.insertEdge(parent, null, "34", v4, v1);
        } finally {
            graph.getModel().endUpdate();
        }

        mxGraphComponent graphComponent = new mxGraphComponent(graph);
        graphComponent.setEnabled(false);
        graphComponent.setBackgroundImage(new ImageIcon(getClass().getResource("/UI/MapaMundo.png")));
        mxGraphModel graphModel = (mxGraphModel) graphComponent.getGraph().getModel();
        Collection<Object> cells = graphModel.getCells().values();
        mxUtils.setCellStyles(graphComponent.getGraph().getModel(),
                cells.toArray(), mxConstants.STYLE_ENDARROW, mxConstants.NONE);
        //instead of getContentPane().add(new mxGraphComponent(jgxAdapter));
        painelDoMundo.setLayout(new BorderLayout());
        painelDoMundo.add(graphComponent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        painelDoMundo = new javax.swing.JPanel();
        painelDeControle = new javax.swing.JPanel();
        comboBoxGrafosDisponiveis = new javax.swing.JComboBox<>();
        labelGrafosDisponiveis = new javax.swing.JLabel();
        labelAlgoritmosDisponiveis = new javax.swing.JLabel();
        comboBoxAlgoritmosDisponiveis = new javax.swing.JComboBox<>();
        botaoExecutar = new javax.swing.JButton();
        botaoExecutarPassoAPasso = new javax.swing.JButton();
        labelResposta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResposta = new javax.swing.JTextArea();
        barraMenu = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuOpcoesInserirManualmente = new javax.swing.JMenuItem();
        MenuPersonalizar = new javax.swing.JMenu();
        menuPersonalizarEditarEstilo = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Teste");
        setName("TelaTeste"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        painelDoMundo.setPreferredSize(new java.awt.Dimension(1024, 720));

        javax.swing.GroupLayout painelDoMundoLayout = new javax.swing.GroupLayout(painelDoMundo);
        painelDoMundo.setLayout(painelDoMundoLayout);
        painelDoMundoLayout.setHorizontalGroup(
            painelDoMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        painelDoMundoLayout.setVerticalGroup(
            painelDoMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        comboBoxGrafosDisponiveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 1", "Item 2", "Item 3", "Item 4", "Item 1", "Item 2", "Item 3", "Item 4", " ", " " }));

        labelGrafosDisponiveis.setText("Grafos disponíveis");

        labelAlgoritmosDisponiveis.setText("Algoritmos disponíveis");

        comboBoxAlgoritmosDisponiveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoExecutar.setText("Executar");

        botaoExecutarPassoAPasso.setText("Executar passo a passo");

        labelResposta.setText("Resposta");

        textAreaResposta.setEditable(false);
        textAreaResposta.setColumns(20);
        textAreaResposta.setRows(5);
        jScrollPane1.setViewportView(textAreaResposta);

        javax.swing.GroupLayout painelDeControleLayout = new javax.swing.GroupLayout(painelDeControle);
        painelDeControle.setLayout(painelDeControleLayout);
        painelDeControleLayout.setHorizontalGroup(
            painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeControleLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExecutarPassoAPasso))
                .addGap(151, 151, 151)
                .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelGrafosDisponiveis))
                    .addComponent(comboBoxGrafosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelAlgoritmosDisponiveis))
                    .addComponent(comboBoxAlgoritmosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelResposta)
                        .addGap(90, 90, 90))))
        );
        painelDeControleLayout.setVerticalGroup(
            painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeControleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addComponent(botaoExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(botaoExecutarPassoAPasso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addComponent(labelGrafosDisponiveis)
                        .addGap(6, 6, 6)
                        .addComponent(comboBoxGrafosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addGroup(painelDeControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAlgoritmosDisponiveis)
                            .addComponent(labelResposta))
                        .addGap(6, 6, 6)
                        .addComponent(comboBoxAlgoritmosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDeControleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        menuOpcoes.setText("Opções");

        menuOpcoesInserirManualmente.setText("Inserir grafo manualmente");
        menuOpcoesInserirManualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcoesInserirManualmenteActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuOpcoesInserirManualmente);

        barraMenu.add(menuOpcoes);

        MenuPersonalizar.setText("Personalizar");

        menuPersonalizarEditarEstilo.setText("Editar estilo");
        MenuPersonalizar.add(menuPersonalizarEditarEstilo);

        barraMenu.add(MenuPersonalizar);

        Ajuda.setText("Ajuda");
        barraMenu.add(Ajuda);

        Sobre.setText("Sobre");
        barraMenu.add(Sobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelDoMundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDeControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDoMundo, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDeControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcoesInserirManualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcoesInserirManualmenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOpcoesInserirManualmenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenu MenuPersonalizar;
    private javax.swing.JMenu Sobre;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoExecutar;
    private javax.swing.JButton botaoExecutarPassoAPasso;
    private javax.swing.JComboBox<String> comboBoxAlgoritmosDisponiveis;
    private javax.swing.JComboBox<String> comboBoxGrafosDisponiveis;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlgoritmosDisponiveis;
    private javax.swing.JLabel labelGrafosDisponiveis;
    private javax.swing.JLabel labelResposta;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuOpcoesInserirManualmente;
    private javax.swing.JMenuItem menuPersonalizarEditarEstilo;
    private javax.swing.JPanel painelDeControle;
    private javax.swing.JPanel painelDoMundo;
    private javax.swing.JTextArea textAreaResposta;
    // End of variables declaration//GEN-END:variables
}
